"""fix: classification model omission

Revision ID: 02931b8819e5
Revises: 44e097680256
Create Date: 2023-05-16 21:42:19.685361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02931b8819e5'
down_revision = '44e097680256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classifications')
    # ### end Alembic commands ###
