"""update

Revision ID: 262df1cbd85c
Revises: 098f09662802
Create Date: 2023-06-21 20:52:23.491520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262df1cbd85c'
down_revision = '098f09662802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('origins')
    # ### end Alembic commands ###
