"""feat: creation of editors tables

Revision ID: 55590b62d23a
Revises: 52f44d8739fb
Create Date: 2023-12-09 23:47:59.379352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55590b62d23a'
down_revision = '52f44d8739fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('editors')
    # ### end Alembic commands ###
