"""updated editors table

Revision ID: 8ba6ee36d1a8
Revises: b027300a4a31
Create Date: 2023-12-15 14:57:44.863820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba6ee36d1a8'
down_revision = 'b027300a4a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.alter_column('is_developer',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.alter_column('is_developer',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
