"""updated editors table

Revision ID: 93711f5049ec
Revises: e6f81ed349e8
Create Date: 2023-12-15 14:39:58.902679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93711f5049ec'
down_revision = 'e6f81ed349e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
