"""updated editors table

Revision ID: b027300a4a31
Revises: 93711f5049ec
Create Date: 2023-12-15 14:47:26.886505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b027300a4a31'
down_revision = '93711f5049ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_editor_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_editor_login')

    # ### end Alembic commands ###
