"""columns: add is_admin & contribution_point column to editors table, added pending_approval column to food table

Revision ID: fedd6a401e75
Revises: 8ba6ee36d1a8
Create Date: 2024-01-25 11:23:37.144526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedd6a401e75'
down_revision = '8ba6ee36d1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contribution_point', sa.Integer(), nullable=True))

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_approval', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('pending_approval')

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_column('contribution_point')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
